name 'ectg-casa-on-rails'
maintainer 'Steve Nolen'
maintainer_email 'technolengy@gmail.com'
license 'Apache 2.0'
description 'Installs/Configures ectg-casa-on-rails'
long_description 'Installs/Configures ectg-casa-on-rails'
version '0.1.3'

depends 'casa-on-rails'
depends 'mysql'
depends 'ruby_rbenv'
depends 'ruby_build'
depends 'nodejs'
depends 'nginx'
depends 'mysql2_chef_gem'
depends 'database'
# depends 'shib-oauth2-bridge'
