name 'mwser-casa-on-rails'
maintainer 'Steve Nolen'
maintainer_email 'technolengy@gmail.com'
license 'Apache 2.0'
description 'Installs/Configures mwser-casa-on-rails'
long_description 'Installs/Configures mwser-casa-on-rails'
version '0.2.16'

depends 'casa-on-rails'
depends 'mysql'
depends 'ruby_rbenv'
depends 'ruby_build'
depends 'nodejs'
depends 'nginx'
depends 'mysql2_chef_gem'
depends 'database'
